# Generated by Django 4.2.6 on 2023-10-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_rename_keyword_webdata_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdata',
            name='images',
            field=models.TextField(blank=True),
        ),
    ]
